{{- if and .Values.vlApi.mlisAuth.enabled (not .Values.vlApi.mlisAuth.existingSecret) .Values.vlApi.mlisAuth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paddleocr-vl-pipeline.vlapi.fullname" . }}-mlis-auth
  labels:
    {{- include "paddleocr-vl-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: vl-api
type: Opaque
data:
  api-key: {{ .Values.vlApi.mlisAuth.apiKey | b64enc }}
{{- end }}
